### ISSUE TITLE
Someone has registered dojot/device-manager with the SCAN project

### ISSUE THREAD

**Issue by oyebodeg** [dojot/device-manager#55]
Hi,

A user with email address "rascaraficci" <raugusto@cpqd.con.br> has requested to be maintainer of this project with the SCAN service at https://scan.coverity.com.  I can not find this user amongst the project's contributors so I am double checking.

Also requested dojot/docker-monitor

Please reply to scan-admin@coverity.com to approve or deny the request

**Comment by rascaraficci** [comment]
Hi,

My profile was not public, but I changed it. I am member of dojot team which is responsible for dojot/device-manager and dojo/docker-monitor.

BR,
